"""Data models for terminal description YAML files."""

from pathlib import Path

from pydantic import BaseModel, Field


class Identity(BaseModel):
    """Terminal identity information."""

    vendor_id: int = Field(description="Vendor ID")
    product_code: int = Field(description="Product code")
    revision_number: int = Field(description="Revision number")


class SymbolNode(BaseModel):
    """Symbol node definition."""

    name_template: str = Field(
        description="Name template with optional {channel} placeholder"
    )
    index_group: int = Field(description="ADS index group")
    size: int = Field(description="Data size in bytes")
    ads_type: int = Field(description="ADS data type")
    type_name: str = Field(description="Type name")
    channels: int = Field(default=1, description="Number of channels")


class TerminalType(BaseModel):
    """Terminal type definition."""

    description: str = Field(description="Terminal description")
    identity: Identity = Field(description="Terminal identity")
    symbol_nodes: list[SymbolNode] = Field(
        default_factory=list, description="List of symbol nodes"
    )


class TerminalConfig(BaseModel):
    """Root configuration for terminal types."""

    terminal_types: dict[str, TerminalType] = Field(
        default_factory=dict, description="Dictionary of terminal types by ID"
    )

    @classmethod
    def from_yaml(cls, path: Path) -> "TerminalConfig":
        """Load configuration from YAML file.

        Args:
            path: Path to YAML file

        Returns:
            TerminalConfig instance
        """
        import yaml

        with path.open() as f:
            data = yaml.safe_load(f)
        return cls.model_validate(data)

    def to_yaml(self, path: Path) -> None:
        """Save configuration to YAML file.

        Args:
            path: Path to save YAML file
        """
        import yaml

        # Convert to dict and write with nice formatting
        data = self.model_dump(exclude_none=True)

        with path.open("w") as f:
            # Write header comment
            f.write("# Terminal Configuration\n")
            f.write("# " + "=" * 56 + "\n")
            f.write("# Automatically generated by catio_terminals\n\n")

            # Write YAML with RedHat YAML extension formatting standards
            yaml.dump(
                data,
                f,
                default_flow_style=False,
                sort_keys=False,
                indent=2,
                width=80,
                allow_unicode=True,
                explicit_start=False,
                explicit_end=False,
            )

    def add_terminal(self, terminal_id: str, terminal: TerminalType) -> None:
        """Add a new terminal type.

        Args:
            terminal_id: Terminal identifier (e.g., "EL4004")
            terminal: TerminalType instance
        """
        self.terminal_types[terminal_id] = terminal

    def remove_terminal(self, terminal_id: str) -> None:
        """Remove a terminal type.

        Args:
            terminal_id: Terminal identifier to remove
        """
        if terminal_id in self.terminal_types:
            del self.terminal_types[terminal_id]
